### ISSUE TITLE
How to get user?

### ISSUE THREAD

**Issue by mylastore** [watscho/express-mongodb-rest-api-boilerplate#17]
First of all thank you for sharing this awesome repo ;)

Sign-in endpoint returns token. How do I get the user data?

**Comment by watscho** [comment]
Hello, thanks <3
https://github.com/watscho/todo-app auth example with that repo

https://github.com/watscho/todo-app/blob/master/todo/src/%40redux/sagas/auth.js
https://github.com/watscho/todo-app/blob/master/todo/src/services/authService.js
https://github.com/watscho/todo-app/blob/master/todo/src/tools/cFetch.js

**Comment by mylastore** [comment]
Thank you

**Comment by felri** [comment]
@watscho first thank you for this great project, can you please post the repo mentioned again? I'm getting a 404 and I can't seem to be able do use the access_token to get the user via postman, I put the access token with Bearer first but it doesn't work.

**Comment by watscho** [comment]
always welcome <3

export const ifetch = (url, { options = {}, accessToken = '' } = {}) =>
  fetch(url, {
    method: 'GET',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      'Accept-Language': 'en',
      Authorization: `Bearer ${accessToken}`,
      ...options.headers
    }
  })

export const authService = {
  fetchUser: async ({ cookies }) => {
    const { accessToken } = cookies

    if (!accessToken)
      return {
        data: undefined,
        ok: true,
        status: 200
      }

    const url = process.env.API_AUTH_USER

    const response = await ifetch(url, { accessToken })

    const data = await response.json()

    return {
      data,
      ok: response.ok,
      status: response.status
    }
  }
}
