### ISSUE TITLE
Missing Documentation? 

### ISSUE THREAD

**Issue by nakul-malhotra** [watscho/express-mongodb-rest-api-boilerplate#26]
Hi ,

Thanks so much for creating this - really easy to build off of! 

I was wondering if you have any docs on making requests to the api? I noticed you mentioned a todo app but I can't find it!

Thanks again.

Nakul

**Comment by nakul-malhotra** [comment]
Also, could you post the expected mongodb structure for this?

**Comment by watscho** [comment]
its just rest api
