### ISSUE TITLE
How can I use the token?

### ISSUE THREAD

**Issue by limadantas** [watscho/express-mongodb-rest-api-boilerplate#28]
When I sing-in I get a token, but I couldn't use it.

I tried: {
"context": {"user": "====token_here==="}
}

How can I perform it?

Thank you

**Comment by watscho** [comment]
https://github.com/watscho/express-mongodb-rest-api-boilerplate/blob/master/workspacess/api/src/middleware/authentication.js

try this

  fetch(http://localhost:8000/user, {
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${accessToken}`
    }
  })

**Comment by limadantas** [comment]
I tried and it said I must be authorized yet.

When I debug, I saw req.context is empty.

**Comment by limadantas** [comment]
Thank you, It worked like a charm!
