### ISSUE TITLE
Add Swagger

### ISSUE THREAD

**Issue by burhanahmed92** [watscho/express-mongodb-rest-api-boilerplate#31]
I like the boilerplate structure but i have a question. How do you add swagger in this structure? All your controllers are functions. Swagger needs class

**Comment by watscho** [comment]
Hello.
In Node.js it is possible to separate Swagger logic from controller code. One approach is to use the swagger-ui-express and swagger-jsdoc packages to define your API documentation using the OpenAPI specification, and then use middleware to validate incoming requests against the spec.

**Comment by watscho** [comment]
i would like to close this issue
